#@overlay/match by=overlay.subset({"kind": "CustomResourceDefinition", "metadata":{"name":"knativeservings.operator.knative.dev"}, "spec":{"conversion":{"strategy":"Webhook"}}}),expects="0+"
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
spec:
  #@overlay/match missing_ok=True
  conversion:
    #@overlay/match missing_ok=True
    webhook:
      #@overlay/match missing_ok=True
      clientConfig:
        #@overlay/match missing_ok=True
        service:
          #@overlay/match missing_ok=True
          namespace: #@ data.values.namespace

#@overlay/match by=overlay.subset({"kind": "CustomResourceDefinition", "metadata":{"name":"knativeeventings.operator.knative.dev"}, "spec":{"conversion":{"strategy":"Webhook"}}}),expects="0+"
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
spec:
  #@overlay/match missing_ok=True
  conversion:
    #@overlay/match missing_ok=True
    webhook:
      #@overlay/match missing_ok=True
      clientConfig:
        #@overlay/match missing_ok=True
        service:
          #@overlay/match missing_ok=True
          namespace: #@ data.values.namespace
