#@ load("@ytt:overlay", "overlay")
#@ load("@ytt:data", "data")

#@overlay/match by=overlay.subset({"kind": "KnativeServing"}),expects=1
---
apiVersion: operator.knative.dev/v1beta1
kind: KnativeServing
metadata:
  #@overlay/match missing_ok=True
  namespace: #@ data.values.namespace
#@overlay/match missing_ok=True
spec:
  #@overlay/match missing_ok=True
  ingress:
    #@overlay/match missing_ok=True
    kourier:
      #@overlay/match missing_ok=True
      enabled: #@ data.values.kourier
    #@overlay/match missing_ok=True
    istio:
      #@overlay/match missing_ok=True
      enabled: #@ data.values.istio
    #@overlay/match missing_ok=True
    contour:
      #@overlay/match missing_ok=True
      enabled: #@ data.values.contour
  #@overlay/match missing_ok=True
  config:
    #@overlay/match missing_ok=True
    network:
      #@overlay/match missing_ok=True
      ingress-class: #@ data.values.ingressClass
